const LOG_IN = 'LOG_IN';
const LOG_IN_FAILED = 'LOG_IN_FAILED';
const LOG_OUT = 'LOG_OUT';
const REGISTER = 'REGISTER';
const REGISTER_FAILED = 'REGISTER_FAILED';

const FETCH_LEVEL_ACCESS = 'FETCH_LEVEL_ACCESS';
const PATCH_PROJECT_END = 'PATCH_PROJECT_END';
const FETCH_PROJECTS = 'FETCH_PROJECTS';
const ADD_PROJECTS = 'ADD_PROJECTS';
const ADD_PROJECTS_FAILED = 'ADD_PROJECTS_FAILED';
const ADD_PBITEM_FAILED = 'ADD_PROJECTS_FAILED';
const CLEAR_PROJECT = 'CLEAR_PROJECT';
const FETCH_PROJECTS_FINISHED = 'FETCH_PROJECTS_FINISHED';
const FETCH_PROJECT_DETAIL = 'FETCH_PROJECT_DETAIL';
const FETCH_PROJECT_OWNER = 'FETCH_PROJECT_OWNER';

const FETCH_PBITEM = 'FETCH_PBITEM';
const FETCH_PBITEM_ID = 'FETCH_PBITEM_ID';
const FETCH_PROJECTS_PRODUCT_OWNER = 'FETCH_PROJECTS_PRODUCT_OWNER';
const ADD_PBITEM = 'ADD_PBITEM';

const FETCH_SPRINTS = 'FETCH_SPRINTS';
const PATCH_SPRINT_END = 'PATCH_SPRINT_END';
const PATCH_SPRINT_START = 'PATCH_SPRINT_START';
const INIT_SPRINT = 'INIT_SPRINT';

const FETCH_RETROSPECTIVE = 'FETCH_RETROSPECTIVE';
const ADD_RETROSPECTIVE = 'ADD_RETROSPECTIVE';
const ADD_RETROSPECTIVE_FAILED = 'ADD_RETROSPECTIVE_FAILED';

const ADD_PROJECT_TEAM = 'ADD_PROJECT_TEAM';
const DELETE_PROJECT_TEAM = 'DELETE_PROJECT_TEAM';
const FETCH_PROJECT_TEAM = 'FETCH_PROJECT_TEAM';
const UPDATE_PROJECT_TEAM = 'UPDATE_PROJECT_TEAM';

const ADD_USER_STORY = 'ADD_USER_STORY';
const ADD_USER_STORY_FAILED = 'ADD_USER_STORY_FAILED';
const FETCH_USER_STORY_ID = 'FETCH_USER_STORY_ID';
const FETCH_USER_STORY = 'FETCH_USER_STORY';
const COUNT_USER_STORY = 'COUNT_USER_STORY';

const FETCH_TASK = 'FETCH_TASK';
const ADD_TASK = 'ADD_TASK';
const ADD_TASK_FAILED = 'ADD_TASK_FAILED';
const FETCH_PROJECT_TASK = 'FETCH_PROJECT_TASK';
const PATCH_TASK = 'PATCH_TASK';

module.exports = {
  LOG_IN,
  LOG_IN_FAILED,
  LOG_OUT,
  REGISTER,
  REGISTER_FAILED,
  FETCH_PROJECTS,
  FETCH_PROJECTS_FINISHED,
  FETCH_PROJECT_DETAIL,
  FETCH_PROJECT_OWNER,

  FETCH_LEVEL_ACCESS,
  ADD_PROJECTS,
  ADD_PROJECTS_FAILED,
  PATCH_PROJECT_END,
  CLEAR_PROJECT,

  FETCH_PBITEM,
  FETCH_PBITEM_ID,
  ADD_PBITEM,
  ADD_PBITEM_FAILED,

  FETCH_SPRINTS,
  INIT_SPRINT,
  PATCH_SPRINT_END,
  PATCH_SPRINT_START,

  FETCH_RETROSPECTIVE,
  ADD_RETROSPECTIVE,
  ADD_RETROSPECTIVE_FAILED,

  DELETE_PROJECT_TEAM,
  FETCH_PROJECT_TEAM,
  FETCH_PROJECTS_PRODUCT_OWNER,
  UPDATE_PROJECT_TEAM,
  ADD_PROJECT_TEAM,

  ADD_USER_STORY,
  ADD_USER_STORY_FAILED,
  FETCH_USER_STORY_ID,
  FETCH_USER_STORY,
  COUNT_USER_STORY,

  FETCH_TASK,
  ADD_TASK,
  ADD_TASK_FAILED,
  FETCH_PROJECT_TASK,
  PATCH_TASK,
};
